from typing import Any

from .spec import Spec
from .types import ServiceKey

__all__ = ["ServiceCommon"]

class ServiceCommon:
    @classmethod
    def factory_name(cls) -> str: ...
    def __init__(self, spec: Spec | None = None) -> None: ...
    @property
    def spec(self) -> Spec: ...
    @property
    def name(self) -> str: ...
    @property
    def readable_name(self) -> str: ...
    @property
    def key(self) -> ServiceKey: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
