from loomi.service.exceptions import ServiceError

__all__ = ["CreationError", "StateError", "SpecError"]

class CreationError(Exception): ...
class StateError(ServiceError): ...
class SpecError(ServiceError): ...
