__all__ = ["AppCommon"]

class AppCommon:
    @classmethod
    def factory_name(cls) -> str: ...
    def __init__(self) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def readable_name(self) -> str: ...
