from abc import ABC
from types import TracebackType
from typing import Any, Self

from .base import Service, ServiceKey, ServiceState, Spec

__all__ = [
    "CommonServiceProtocol",
    "SyncServiceInitializerProtocol",
    "AsyncServiceInitializerProtocol",
    "ServiceComposerProtocol",
    "ServiceProtocol",
    "AsyncServiceProtocol",
    "SyncServiceProtocol",
]

class CommonServiceProtocol(ABC):
    @classmethod
    def factory_name(cls) -> str: ...
    @property
    def spec(self) -> Spec: ...
    @property
    def name(self) -> str: ...
    @property
    def readable_name(self) -> str: ...
    @property
    def key(self) -> ServiceKey: ...
    @property
    def service_state(self) -> ServiceState: ...
    @property
    def is_initialized(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...

class SyncServiceInitializerProtocol(ABC):
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def setup(self) -> None: ...
    def cleanup(self) -> None: ...
    def pre_initialize(self) -> None: ...
    def post_initialize(self) -> None: ...
    def pre_shutdown(self) -> None: ...
    def post_shutdown(self) -> None: ...

class AsyncServiceInitializerProtocol(ABC):
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    async def setup(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def pre_initialize(self) -> None: ...
    async def post_initialize(self) -> None: ...
    async def pre_shutdown(self) -> None: ...
    async def post_shutdown(self) -> None: ...

class ServiceComposerProtocol(ABC):
    def add_dependency(self, name: str, spec: Spec) -> Service: ...
    def get_dependency(self, name: str) -> Service: ...
    def get_dependencies(self) -> dict[str, "Service"]: ...
    def get_dependents(self) -> set["Service"]: ...
    def detach_dependent(self, dependent: Service) -> None: ...

class ServiceProtocol(CommonServiceProtocol, ServiceComposerProtocol): ...
class AsyncServiceProtocol(ServiceProtocol, AsyncServiceInitializerProtocol): ...
class SyncServiceProtocol(ServiceProtocol, SyncServiceInitializerProtocol): ...
