"""Generic collection protocols and ops."""

from .collection import CollectionBase, CollectionProtocol
from .container import ContainerBase, ContainerProtocol
from .iterable import IterableBase, IterableProtocol
from .mapping import MappingBase, MappingProtocol, MutableMappingBase, MutableMappingProtocol
from .mapping_ops import (
    DeleteItemCmd,
    DictPopCmd,
    GetOp,
    ItemsOp,
    KeysOp,
    PopItemCmd,
    SetDefaultCmd,
    SetItemCmd,
    UpdateCmd,
    ValuesOp,
)
from .sequence import MutableSequenceBase, MutableSequenceProtocol, SequenceBase, SequenceProtocol
from .sequence_ops import (
    AppendCmd,
    CountOp,
    ExtendCmd,
    FirstOp,
    IndexOfOp,
    InsertCmd,
    LastOp,
    PopCmd,
    RemoveValueCmd,
    ReverseCmd,
)
from .set_ import MutableSetBase, MutableSetProtocol, SetLikeBase, SetLikeProtocol
from .set_ops import (
    AddCmd,
    DifferenceOp,
    DifferenceUpdateCmd,
    DiscardCmd,
    IntersectionOp,
    IntersectionUpdateCmd,
    IsDisjointOp,
    IsSubsetOp,
    IsSupersetOp,
    RemoveCmd,
    SetPopCmd,
    SetUpdateCmd,
    SymmetricDifferenceOp,
    SymmetricDifferenceUpdateCmd,
    UnionOp,
)
from .shared_ops import ClearCmd
from .sized import SizedBase, SizedProtocol


__all__ = [
    "AddCmd",
    "AppendCmd",
    "ClearCmd",
    "CollectionBase",
    "CollectionProtocol",
    "ContainerBase",
    "ContainerProtocol",
    "CountOp",
    "DeleteItemCmd",
    "DictPopCmd",
    "DifferenceOp",
    "DifferenceUpdateCmd",
    "DiscardCmd",
    "ExtendCmd",
    "FirstOp",
    "GetOp",
    "IndexOfOp",
    "InsertCmd",
    "IntersectionOp",
    "IntersectionUpdateCmd",
    "IsDisjointOp",
    "IsSubsetOp",
    "IsSupersetOp",
    "ItemsOp",
    "IterableBase",
    "IterableProtocol",
    "KeysOp",
    "LastOp",
    "MappingBase",
    "MappingProtocol",
    "MutableMappingBase",
    "MutableMappingProtocol",
    "MutableSequenceBase",
    "MutableSequenceProtocol",
    "MutableSetBase",
    "MutableSetProtocol",
    "PopCmd",
    "PopItemCmd",
    "RemoveCmd",
    "RemoveValueCmd",
    "ReverseCmd",
    "SequenceBase",
    "SequenceProtocol",
    "SetDefaultCmd",
    "SetItemCmd",
    "SetLikeBase",
    "SetLikeProtocol",
    "SetPopCmd",
    "SetUpdateCmd",
    "SizedBase",
    "SizedProtocol",
    "SymmetricDifferenceOp",
    "SymmetricDifferenceUpdateCmd",
    "UnionOp",
    "UpdateCmd",
    "ValuesOp",
]
