from typing import Any, AsyncGenerator, Protocol

from loomistd.observer import ObserverProtocol, SubscriptionProtocol
from loomistd.storage import StorageProtocol, TransactionContextManagerProtocol, TransactionProtocol

from ._types import StateCallbackFn, StateKey, StateValue

__all__ = ["StateProtocol"]

class StateProtocol(Protocol):
    @property
    def storage(self) -> StorageProtocol[StateKey, StateValue, Any, Any]: ...
    @property
    def observer(self) -> ObserverProtocol[StateKey, Any]: ...
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(
        self, key: StateKey, callback: StateCallbackFn
    ) -> SubscriptionProtocol[StateKey]: ...
    async def unsubscribe(self, subscription: SubscriptionProtocol[StateKey]) -> None: ...
    async def begin_transaction(self) -> TransactionProtocol[StateKey, StateValue]: ...
    async def transaction(self) -> TransactionContextManagerProtocol[StateKey, StateValue]: ...
