from dataclasses import dataclass
from types import TracebackType
from typing import Any, AsyncGenerator

from loomi.service import AsyncService, Spec
from loomistd.observer import BaseObserverSpec, ObserverProtocol, SubscriptionProtocol
from loomistd.storage import (
    BaseStorageSpec,
    StorageProtocol,
    TransactionContextManagerProtocol,
    TransactionProtocol,
)

from ._types import StateCallbackFn, StateKey, StateValue

__all__ = ["State", "StateSpec", "StateTransaction", "StateTransactionContextManager"]

class StateSpec(Spec):
    storage: BaseStorageSpec
    observer: BaseObserverSpec
    @classmethod
    def identity_fields(cls): ...

class State(AsyncService):
    @property
    def storage(self) -> StorageProtocol[StateKey, StateValue, Any, Any]: ...
    @property
    def observer(self) -> ObserverProtocol[StateKey, Any]: ...
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(
        self, key: StateKey, callback: StateCallbackFn
    ) -> SubscriptionProtocol[StateKey]: ...
    async def unsubscribe(self, subscription: SubscriptionProtocol[StateKey]) -> None: ...
    async def begin_transaction(self) -> StateTransaction: ...
    async def transaction(self) -> StateTransactionContextManager: ...

@dataclass
class StateTransaction(TransactionProtocol[StateKey, StateValue]):
    storage_txn: TransactionProtocol[StateKey, StateValue]
    observer: ObserverProtocol[StateKey, Any]
    modified_keys: set[StateKey] = ...
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def __init__(self, storage_txn, observer, modified_keys=...) -> None: ...

@dataclass
class StateTransactionContextManager(TransactionContextManagerProtocol[StateKey, StateValue]):
    async def __aenter__(self) -> StateTransaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...
    def __init__(self, _state, _transaction=...) -> None: ...
