[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "loomi"
version = "0.2.0"
description = "loomi"
authors = ["Gor Arakelyan <gorarkln@gmail.com>"]
readme = "README.md"
packages = [
    { include = "loomi", from = "src" },
    { include = "loomicore", from = "src" },
    { include = "loomistd", from = "pkgs" },
    { include = "loomiverse", from = "pkgs" },
]
include = []

[tool.poetry.scripts]
loomix = "loomix.cli.entrypoint:loomix"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.9.4"
aiofile = "^3.9.0"
lmdb = "^1.6.2"
aiohttp = "^3.11.13"
requests = "^2.32.3"
pre-commit = "^4.1.0"
networkx = "^3.4.2"
rich-click = "^1.8.8"
rpyc = "^6.0.2"
msgpack = "^1.1.1"
wrapt = "^1.17.2"
pyinstrument = "^5.0.1"
matplotlib = "^3.10.1"
scipy = "^1.15.2"
mermaid-py = "^0.7.1"
streamlit = "^1.44.1"
streamlit-flow-component = "^1.6.1"
graphviz = "^0.20.3"
py-spy = "^0.4.0"
psutil = "^7.0.0"
ray = "^2.46.0"


[tool.poetry.group.dev.dependencies]
autoflake = "*"
black = "*"
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
known_first_party = ["loomi", "loomicore", "loomistd", "loomiverse"]

[tool.autoflake]
check = false
recursive = true
remove_all_unused_imports = true
ignore_init_module_imports = true
remove_unused_variables = true
ignore_pass_statements = false
ignore_pass_after_docstring = true
in_place = true
