"""Generic collection interfaces and interactions."""

from .collection import CollectionForm
from .container import ContainerForm
from .iterable import IterableForm
from .mapping import MappingForm, MutableMappingForm, ReactiveMappingForm
from .mapping_interactions import (
    ContainsKeyQuery,
    DeleteItemCommand,
    DictPopAction,
    GetQuery,
    ItemsQuery,
    KeysQuery,
    MergeQuery,
    MergeUpdateAction,
    PopItemAction,
    ReversedKeysQuery,
    SetDefaultAction,
    SetItemCommand,
    UpdateCommand,
    ValuesQuery,
)
from .sequence import MutableSequenceForm, ReactiveSequenceForm, SequenceForm
from .sequence_interactions import (
    AppendCommand,
    CountQuery,
    DelIndexCommand,
    ExtendCommand,
    FirstQuery,
    IAddAction,
    IMulAction,
    IndexOfQuery,
    InsertCommand,
    LastQuery,
    PopAction,
    RemoveValueCommand,
    ReverseCommand,
    SetIndexCommand,
    SortCommand,
)
from .set_ import MutableSetForm, ReactiveSetForm, SetLikeForm
from .set_interactions import (
    AddCommand,
    DifferenceQuery,
    DifferenceUpdateCommand,
    DiscardCommand,
    IntersectionQuery,
    IntersectionUpdateCommand,
    IsDisjointQuery,
    IsSubsetQuery,
    IsSupersetQuery,
    RemoveCommand,
    SetAndQuery,
    SetIAndAction,
    SetIOrAction,
    SetISubAction,
    SetIXorAction,
    SetOrQuery,
    SetPopAction,
    SetSubQuery,
    SetUpdateCommand,
    SetXorQuery,
    SymmetricDifferenceQuery,
    SymmetricDifferenceUpdateCommand,
    UnionQuery,
)
from .shared_interactions import ClearCommand
from .sized import SizedForm
from .sliceable import SliceableForm


__all__ = [
    "AddCommand",
    "AppendCommand",
    "ClearCommand",
    "CollectionForm",
    "ContainerForm",
    "ContainsKeyQuery",
    "CountQuery",
    "DelIndexCommand",
    "DeleteItemCommand",
    "DictPopAction",
    "DifferenceQuery",
    "DifferenceUpdateCommand",
    "DiscardCommand",
    "ExtendCommand",
    "FirstQuery",
    "GetQuery",
    "IAddAction",
    "IMulAction",
    "IndexOfQuery",
    "InsertCommand",
    "IntersectionQuery",
    "IntersectionUpdateCommand",
    "IsDisjointQuery",
    "IsSubsetQuery",
    "IsSupersetQuery",
    "ItemsQuery",
    "IterableForm",
    "KeysQuery",
    "LastQuery",
    "MappingForm",
    "MergeQuery",
    "MergeUpdateAction",
    "MutableMappingForm",
    "MutableSequenceForm",
    "MutableSetForm",
    "PopAction",
    "PopItemAction",
    "ReactiveMappingForm",
    "ReactiveSequenceForm",
    "ReactiveSetForm",
    "RemoveCommand",
    "RemoveValueCommand",
    "ReverseCommand",
    "ReversedKeysQuery",
    "SequenceForm",
    "SetAndQuery",
    "SetDefaultAction",
    "SetIAndAction",
    "SetIOrAction",
    "SetISubAction",
    "SetIXorAction",
    "SetIndexCommand",
    "SetItemCommand",
    "SetLikeForm",
    "SetOrQuery",
    "SetPopAction",
    "SetSubQuery",
    "SetUpdateCommand",
    "SetXorQuery",
    "SizedForm",
    "SliceableForm",
    "SortCommand",
    "SymmetricDifferenceQuery",
    "SymmetricDifferenceUpdateCommand",
    "UnionQuery",
    "UpdateCommand",
    "ValuesQuery",
]
