"""Collection structural morphisms — sequence, mapping, set operations."""

from .mapping import (
    CopyOp,
    DeleteItemCmd,
    DictPopCmd,
    GetOp,
    ItemsOp,
    KeyAtOp,
    KeysOp,
    PopItemCmd,
    SetDefaultCmd,
    SetItemCmd,
    UpdateCmd,
    ValuesOp,
)
from .sequence import (
    AppendCmd,
    CountOp,
    ExtendCmd,
    FirstOp,
    IndexOfOp,
    InsertCmd,
    LastOp,
    PopCmd,
    RemoveValueCmd,
)
from .set import (
    AddCmd,
    DifferenceOp,
    DifferenceUpdateCmd,
    DiscardCmd,
    IntersectionOp,
    IntersectionUpdateCmd,
    IsDisjointOp,
    IsSubsetOp,
    IsSupersetOp,
    RemoveCmd,
    SetPopCmd,
    SetUpdateCmd,
    SymmetricDifferenceOp,
    SymmetricDifferenceUpdateCmd,
    UnionOp,
)
from .shared import ClearCmd


__all__ = [
    "AddCmd",
    "AppendCmd",
    "ClearCmd",
    "CopyOp",
    "CountOp",
    "DeleteItemCmd",
    "DictPopCmd",
    "DifferenceOp",
    "DifferenceUpdateCmd",
    "DiscardCmd",
    "ExtendCmd",
    "FirstOp",
    "GetOp",
    "IndexOfOp",
    "InsertCmd",
    "IntersectionOp",
    "IntersectionUpdateCmd",
    "IsDisjointOp",
    "IsSubsetOp",
    "IsSupersetOp",
    "ItemsOp",
    "KeyAtOp",
    "KeysOp",
    "LastOp",
    "PopCmd",
    "PopItemCmd",
    "RemoveCmd",
    "RemoveValueCmd",
    "SetDefaultCmd",
    "SetItemCmd",
    "SetPopCmd",
    "SetUpdateCmd",
    "SymmetricDifferenceOp",
    "SymmetricDifferenceUpdateCmd",
    "UnionOp",
    "UpdateCmd",
    "ValuesOp",
]
