"""Computations module - operations and commands for the term layer.

This module provides all computation operations organized by domain:

Submodules:
- bases: Foundation tier (UnaryOp, BinaryOp, TernaryOp base classes)
- value: Value operations (arithmetic, comparison, logical, conversion)
- types: Type-specific operations (string, bytes, sequence, mapping, set)
- ref: Reference operations (access, query, functional, search)
- command: Command operations (core, sequence, mapping, set)
- reactive: Reactive operations (OnChangeOp, etc.)
- typed: TypedValue operations (FuncCallOp, MethodCallOp, etc.)

Top-level exports:
- Ref operations (MapOp, FilterOp, etc.) work on LValue references
- Type operations from types/ (sequence, string, etc.) work on RValues
- For sequence value operations, import from comps.types.sequence directly

Note on duplicate names:
- MapOp, FilterOp, ReduceOp at top-level are REF operations (lazy, storage)
- types.sequence has equivalent ops for SEQUENCE VALUES (eager, in-memory)
- Use fully-qualified imports when you need the sequence value versions:
    from everyshape.term.comps.types.sequence import MapOp as SeqMapOp
"""

from . import bases, command, ref, types, value
from .command import (
    AddCmd,
    AppendCmd,
    ClearCmd,
    DeleteCmd,
    DiscardCmd,
    InsertCmd,
    MappingRemoveCmd,
    MappingSetCmd,
    PopCmd,
    RemoveCmd,
    SetCmd,
    StoreCmd,
)
from .reactive import (
    ChangeOp,
    OnChangeOp,
    OnChildChangeOp,
    OnChildrenChangeOp,
    OnDescendantsChangeOp,
    OnPrimitiveChangeOp,
)
from .ref import (
    CountOp,
    ExistsOp,
    ExtractOp,
    FilterItemsOp,
    FilterOp,
    FindIndexOp,
    FindItemOp,
    FindKeyOp,
    FindOp,
    FindValueOp,
    GetOp,
    IndexOp,
    ItemsOp,
    KeysOp,
    LengthOp,
    MapItemsOp,
    MapOp,
    MappingGetOp,
    MapValuesOp,
    MissingOp,
    ReduceItemsOp,
    ReduceOp,
    ValuesOp,
)
from .typed import (
    DelAttrOp,
    FuncCallOp,
    GetAttrOp,
    MethodCallOp,
    SetAttrOp,
    TypedSetCmd,
)
from .types import (
    AllOp,
    AnyOp,
    AtOp,
    BytesCountOp,
    BytesEndsWithOp,
    BytesFindOp,
    BytesLowerOp,
    BytesLStripOp,
    BytesReplaceOp,
    BytesRStripOp,
    BytesSplitOp,
    BytesStartsWithOp,
    BytesStripOp,
    BytesUpperOp,
    CapitalizeOp,
    CenterOp,
    ContainsOp,
    CountSubstringOp,
    DecodeOp,
    DictGetOp,
    DictItemsOp,
    DictKeysOp,
    DictValuesOp,
    DifferenceOp,
    EncodeOp,
    EndsWithOp,
    FirstOp,
    HexOp,
    IndexOfOp,
    IntersectionOp,
    IsAlnumOp,
    IsAlphaOp,
    IsDigitOp,
    IsDisjointOp,
    IsSpaceOp,
    IsSubsetOp,
    IsSupersetOp,
    JoinOp,
    LastOp,
    LenOp,
    LJustOp,
    LowerOp,
    LStripOp,
    MaxOp,
    MinOp,
    ReplaceOp,
    ReversedOp,
    RFindOp,
    RJustOp,
    RSplitOp,
    RStripOp,
    SliceOp,
    SortedOp,
    SplitOp,
    StartsWithOp,
    StringFindOp,
    StripOp,
    SumOp,
    SwapCaseOp,
    SymmetricDifferenceOp,
    TitleOp,
    UnionOp,
    UpperOp,
    ZFillOp,
)
from .value import (
    AbsOp,
    AddOp,
    AndOp,
    BinaryOp,
    BitwiseAndOp,
    BitwiseNotOp,
    BitwiseOrOp,
    BoolOp,
    ConditionalOp,
    ConversionOp,
    DivOp,
    EqOp,
    FloorDivOp,
    GeOp,
    GtOp,
    IdCompOp,
    IsEmptyOp,
    IsNaNOp,
    LeOp,
    LShiftOp,
    LtOp,
    ModOp,
    MulOp,
    NegOp,
    NeOp,
    NotEmptyOp,
    NotNaNOp,
    NotOp,
    OrOp,
    PosOp,
    PowOp,
    RShiftOp,
    SubOp,
    TernaryOp,
    ToBoolOp,
    ToBytesOp,
    ToFloatOp,
    ToIntOp,
    ToListOp,
    ToSetOp,
    ToStrOp,
    ToTupleOp,
    UnaryOp,
    XorOp,
)


__all__ = [
    # Value ops
    "AbsOp",
    # Command ops
    "AddCmd",
    "AddOp",
    # Type-specific ops
    "AllOp",
    "AndOp",
    "AnyOp",
    "AppendCmd",
    "AtOp",
    "BinaryOp",
    "BitwiseAndOp",
    "BitwiseNotOp",
    "BitwiseOrOp",
    "BoolOp",
    "BytesCountOp",
    "BytesEndsWithOp",
    "BytesFindOp",
    "BytesLStripOp",
    "BytesLowerOp",
    "BytesRStripOp",
    "BytesReplaceOp",
    "BytesSplitOp",
    "BytesStartsWithOp",
    "BytesStripOp",
    "BytesUpperOp",
    "CapitalizeOp",
    "CenterOp",
    # Reactive ops
    "ChangeOp",
    "ClearCmd",
    "ConditionalOp",
    "ContainsOp",
    "ConversionOp",
    # Ref ops
    "CountOp",
    "CountSubstringOp",
    "DecodeOp",
    # Typed ops
    "DelAttrOp",
    "DeleteCmd",
    "DictGetOp",
    "DictItemsOp",
    "DictKeysOp",
    "DictValuesOp",
    "DifferenceOp",
    "DiscardCmd",
    "DivOp",
    "EncodeOp",
    "EndsWithOp",
    "EqOp",
    "ExistsOp",
    "ExtractOp",
    "FilterItemsOp",
    "FilterOp",
    "FindIndexOp",
    "FindItemOp",
    "FindKeyOp",
    "FindOp",
    "FindValueOp",
    "FirstOp",
    "FloorDivOp",
    "FuncCallOp",
    "GeOp",
    "GetAttrOp",
    "GetOp",
    "GtOp",
    "HexOp",
    "IdCompOp",
    "IndexOfOp",
    "IndexOp",
    "InsertCmd",
    "IntersectionOp",
    "IsAlnumOp",
    "IsAlphaOp",
    "IsDigitOp",
    "IsDisjointOp",
    "IsEmptyOp",
    "IsNaNOp",
    "IsSpaceOp",
    "IsSubsetOp",
    "IsSupersetOp",
    "ItemsOp",
    "JoinOp",
    "KeysOp",
    "LJustOp",
    "LShiftOp",
    "LStripOp",
    "LastOp",
    "LeOp",
    "LenOp",
    "LengthOp",
    "LowerOp",
    "LtOp",
    "MapItemsOp",
    "MapOp",
    "MapValuesOp",
    "MappingGetOp",
    "MappingRemoveCmd",
    "MappingSetCmd",
    "MaxOp",
    "MethodCallOp",
    "MinOp",
    "MissingOp",
    "ModOp",
    "MulOp",
    "NeOp",
    "NegOp",
    "NotEmptyOp",
    "NotNaNOp",
    "NotOp",
    "OnChangeOp",
    "OnChildChangeOp",
    "OnChildrenChangeOp",
    "OnDescendantsChangeOp",
    "OnPrimitiveChangeOp",
    "OrOp",
    "PopCmd",
    "PosOp",
    "PowOp",
    "RFindOp",
    "RJustOp",
    "RShiftOp",
    "RSplitOp",
    "RStripOp",
    "ReduceItemsOp",
    "ReduceOp",
    "RemoveCmd",
    "ReplaceOp",
    "ReversedOp",
    "SetAttrOp",
    "SetCmd",
    "SliceOp",
    "SortedOp",
    "SplitOp",
    "StartsWithOp",
    "StoreCmd",
    "StringFindOp",
    "StripOp",
    "SubOp",
    "SumOp",
    "SwapCaseOp",
    "SymmetricDifferenceOp",
    "TernaryOp",
    "TitleOp",
    "ToBoolOp",
    "ToBytesOp",
    "ToFloatOp",
    "ToIntOp",
    "ToListOp",
    "ToSetOp",
    "ToStrOp",
    "ToTupleOp",
    "TypedSetCmd",
    "UnaryOp",
    "UnionOp",
    "UpperOp",
    "ValuesOp",
    "XorOp",
    "ZFillOp",
    # Submodules
    "bases",
    "command",
    "ref",
    "types",
    "value",
]
