from dataclasses import dataclass

from .types import ServiceRole

__all__ = ["ServiceContext"]

@dataclass
class ServiceContext:
    original_role: ServiceRole
    active_roles: set[ServiceRole] = ...
    root_usage_count: int = ...
    dependency_usage_count: int = ...
    @property
    def is_active(self) -> bool: ...
    def add_role(self, role: ServiceRole) -> None: ...
    def remove_role(self, role: ServiceRole) -> None: ...
    def __init__(
        self, original_role, active_roles=..., root_usage_count=..., dependency_usage_count=...
    ) -> None: ...
