from loomi.service.exceptions import ServiceError

__all__ = ["CircularDependencyError", "DependencyError", "DependencyNotFoundError"]

class DependencyError(ServiceError): ...
class DependencyNotFoundError(DependencyError): ...
class CircularDependencyError(DependencyError): ...
