from loomi.service.base import Service, Spec
from loomi.service.lib.service_registry import ServiceRegistry

__all__ = ["DependencyManager"]

class DependencyManager:
    def __init__(self, registry: ServiceRegistry) -> None: ...
    def register_service(self, service: Service, is_dependency: bool = False) -> None: ...
    def resolve_dependency(self, parent: Service, name: str, spec: Spec) -> Service: ...
    def add_relationship(self, parent: Service, name: str, child: Service) -> None: ...
    def get_dependencies(self, service: Service) -> dict[str, "Service"]: ...
    def get_dependents(self, service: Service) -> set["Service"]: ...
    def detach_relationship(self, parent: Service, child: Service) -> None: ...
    def can_auto_shutdown(self, service: Service) -> bool: ...
