from _typeshed import Incomplete

from loomi.service.base import Service, ServiceKey

__all__ = ["DependencyNode"]

class DependencyNode:
    service: Incomplete
    context: Incomplete
    dependencies: Incomplete
    dependents: Incomplete
    initiators: Incomplete
    detached_dependents: Incomplete
    def __init__(self, service: Service, is_dependency: bool) -> None: ...
    def register_root(self) -> None: ...
    def unregister_root(self) -> None: ...
    def add_dependent(self, dependent: Service) -> None: ...
    def remove_dependent(self, dependent: Service) -> None: ...
    def add_dependency(self, name: str, dependency: Service) -> None: ...
    def get_dependency(self, name: str) -> Service | None: ...
    def remove_dependency(self, name: str) -> Service | None: ...
    def detach_dependent(self, service: ServiceKey) -> None: ...
