from loomi.service.exceptions import ServiceError

__all__ = ["RegistryError", "RegistryStateError", "RegistryKeyError"]

class RegistryError(ServiceError): ...
class RegistryStateError(RegistryError): ...
class RegistryKeyError(RegistryError): ...
