from loomi.service.base import Service, Spec
from loomi.service.base.state import ServiceState

__all__ = ["ServiceRegistry"]

class ServiceRegistry:
    def __init__(self) -> None: ...
    def get_service(self, spec: Spec) -> Service | None: ...
    def add_service(self, service: Service) -> None: ...
    def remove_service(self, service: Service) -> None: ...
    def get_service_state(self, service: Service) -> ServiceState: ...
    def set_service_state(self, service: Service, state: ServiceState) -> None: ...
