from loomi.service import SyncService

from .types import JSONCodecEncodedKey, JSONCodecEncodedValue, JSONCodecKey, JSONCodecValue

__all__ = ["JSONCodec"]

class JSONCodec(SyncService):
    def encode_key(self, key: JSONCodecKey) -> JSONCodecEncodedKey: ...
    def decode_key(self, encoded: JSONCodecEncodedKey) -> JSONCodecKey: ...
    def encode_value(self, value: JSONCodecValue) -> JSONCodecEncodedValue: ...
    def decode_value(self, encoded: JSONCodecEncodedValue) -> JSONCodecValue: ...
