from loomi.service import SyncService

from .types import BinaryCodecEncodedKey, BinaryCodecEncodedValue, BinaryCodecKey, BinaryCodecValue

__all__ = ["BinaryCodec"]

class BinaryCodec(SyncService):
    def encode_key(self, key: BinaryCodecKey) -> BinaryCodecEncodedKey: ...
    def decode_key(self, encoded: BinaryCodecEncodedKey) -> BinaryCodecKey: ...
    def encode_value(self, value: BinaryCodecValue) -> BinaryCodecEncodedValue: ...
    def decode_value(self, encoded: BinaryCodecEncodedValue) -> BinaryCodecValue: ...
