import logging
from pathlib import Path

INIT: bool

def init_logging() -> None: ...
def setup_logging(log_dir_path: Path, log_level: int = ...): ...
def get_logger(name: str, level: int | None = None) -> logging.Logger: ...
