from types import TracebackType
from typing import Self

from loomi.service.base import SyncService

from .base import ServiceCommonInitializer

__all__ = ["SyncServiceInitializer"]

class SyncServiceInitializer(ServiceCommonInitializer, SyncService):
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def setup(self) -> None: ...
    def cleanup(self) -> None: ...
    def pre_initialize(self) -> None: ...
    def post_initialize(self) -> None: ...
    def pre_shutdown(self) -> None: ...
    def post_shutdown(self) -> None: ...
