from types import TracebackType
from typing import Self

from loomi.service.base import AsyncService

from .base import ServiceCommonInitializer

__all__ = ["AsyncServiceInitializer"]

class AsyncServiceInitializer(ServiceCommonInitializer, AsyncService):
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    async def setup(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def pre_initialize(self) -> None: ...
    async def post_initialize(self) -> None: ...
    async def pre_shutdown(self) -> None: ...
    async def post_shutdown(self) -> None: ...
