from types import TracebackType
from typing import AsyncGenerator, Callable, Generator, Protocol, Self

from .handlers.state.protocols import (
    AsyncStateProtocol,
    AsyncSubscriptionProtocol,
    AsyncTransactionContextManagerProtocol,
    AsyncTransactionProtocol,
    SyncStateProtocol,
    SyncSubscriptionProtocol,
    SyncTransactionContextManagerProtocol,
    SyncTransactionProtocol,
)
from .handlers.state.types import AsyncStateCallbackFn, StateKey, StateValue, SyncStateCallbackFn
from .handlers.tasks.protocols import AsyncOperationProtocol, SyncOperationProtocol

__all__ = [
    "CommonAppProtocol",
    "SyncAppInitializerProtocol",
    "AsyncAppInitializerProtocol",
    "AsyncAppServicesProtocol",
    "SyncAppServicesProtocol",
    "AsyncAppStateProtocol",
    "SyncAppStateProtocol",
    "AsyncAppTasksProtocol",
    "SyncAppTasksProtocol",
    "AsyncAppModelProtocol",
    "SyncAppModelProtocol",
    "AppProtocol",
    "SyncAppProtocol",
    "AsyncAppProtocol",
]

class CommonAppProtocol(Protocol): ...

class SyncAppInitializerProtocol(Protocol):
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class AsyncAppInitializerProtocol(Protocol):
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class AsyncAppServicesProtocol(Protocol):
    async def initialize_services(self) -> None: ...
    async def shutdown_services(self) -> None: ...

class SyncAppServicesProtocol(Protocol):
    def initialize_services(self) -> None: ...
    def shutdown_services(self) -> None: ...

class SyncAppStateProtocol(Protocol):
    @property
    def state(self) -> SyncStateProtocol: ...
    @property
    def s(self) -> SyncStateProtocol: ...
    def get(self, key: StateKey) -> StateValue: ...
    def set(self, key: StateKey, value: StateValue) -> None: ...
    def delete(self, key: StateKey) -> None: ...
    def exists(self, key: StateKey) -> bool: ...
    def list_keys(self, *prefix: str) -> Generator["StateKey", None, None]: ...
    def subscribe(
        self, key: StateKey, callback: SyncStateCallbackFn
    ) -> SyncSubscriptionProtocol: ...
    def unsubscribe(self, subscription: SyncSubscriptionProtocol) -> None: ...
    def begin_transaction(self) -> SyncTransactionProtocol: ...
    def transaction(self) -> SyncTransactionContextManagerProtocol: ...

class AsyncAppStateProtocol(Protocol):
    @property
    def state(self) -> AsyncStateProtocol: ...
    @property
    def s(self) -> AsyncStateProtocol: ...
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, *prefix: str) -> AsyncGenerator["StateKey", None]: ...
    async def subscribe(
        self, key: StateKey, callback: AsyncStateCallbackFn
    ) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(self, subscription: AsyncSubscriptionProtocol) -> None: ...
    async def begin_transaction(self) -> AsyncTransactionProtocol: ...
    async def transaction(self) -> AsyncTransactionContextManagerProtocol: ...

class SyncAppTasksProtocol(Protocol):
    def execute(self, operation: SyncOperationProtocol) -> None: ...
    def function(self, func: Callable, *, name: str | None = None) -> SyncOperationProtocol: ...
    def sequence(
        self, *operations: SyncOperationProtocol, delay: float = 0, continue_on_error: bool = False
    ) -> SyncOperationProtocol: ...

class AsyncAppTasksProtocol(Protocol):
    async def execute(self, operation: AsyncOperationProtocol) -> None: ...
    def function(self, func: Callable, *, name: str | None = None) -> AsyncOperationProtocol: ...
    def sequence(
        self, *operations: AsyncOperationProtocol, delay: float = 0, continue_on_error: bool = False
    ) -> AsyncOperationProtocol: ...

class SyncAppModelProtocol(Protocol): ...
class AsyncAppModelProtocol(Protocol): ...
class AppProtocol(CommonAppProtocol, Protocol): ...
class SyncAppProtocol(
    AppProtocol,
    SyncAppInitializerProtocol,
    SyncAppServicesProtocol,
    SyncAppStateProtocol,
    SyncAppTasksProtocol,
    SyncAppModelProtocol,
    Protocol,
): ...
class AsyncAppProtocol(
    AppProtocol,
    AsyncAppInitializerProtocol,
    AsyncAppServicesProtocol,
    AsyncAppStateProtocol,
    AsyncAppTasksProtocol,
    AsyncAppModelProtocol,
    Protocol,
): ...
