import weakref
from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable, Generic, TypeVar

__all__ = [
    "DescriptorMetadata",
    "DescriptorState",
    "StorageStrategy",
    "ValidationStrategy",
    "validate_type",
]

DescriptorT = TypeVar("DescriptorT")

class StorageStrategy(Enum):
    INSTANCE_DICT = ...
    WEAKREF = ...

class ValidationStrategy(Enum):
    STRICT = ...
    COERCE = ...
    LENIENT = ...

@dataclass(frozen=True)
class DescriptorMetadata(Generic[DescriptorT]):
    doc: str | None = ...
    validator: Callable[[DescriptorT], bool] | None = ...
    storage: StorageStrategy = ...
    validation_strategy: ValidationStrategy = ...
    allow_none: bool = ...
    @property
    def type(self) -> type[DescriptorT]: ...
    @property
    def name(self) -> str: ...
    def __init__(
        self,
        _name=...,
        _type=...,
        doc=...,
        validator=...,
        storage=...,
        validation_strategy=...,
        allow_none=...,
    ) -> None: ...

@dataclass
class DescriptorState:
    values: weakref.WeakKeyDictionary = ...
    def __init__(self, values=...) -> None: ...

def validate_type(value: Any, expected_type: type[DescriptorT]) -> bool: ...
