import weakref
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Generic, TypeVar

__all__ = [
    "DescriptorMetadata",
    "DescriptorState",
    "StorageStrategy",
    "ValidationStrategy",
    "validate_type",
]

DescriptorT = TypeVar("DescriptorT")

class StorageStrategy(Enum):
    INSTANCE_DICT = ...
    WEAKREF = ...

class ValidationStrategy(Enum):
    STRICT = ...
    COERCE = ...
    LENIENT = ...

@dataclass(frozen=True)
class DescriptorMetadata(Generic[DescriptorT]):
    doc: str | None = ...
    validator: Callable[[DescriptorT], bool] | None = ...
    storage: StorageStrategy = ...
    validation_strategy: ValidationStrategy = ...
    allow_none: bool = ...
    @property
    def type(self) -> type[DescriptorT]: ...
    @property
    def name(self) -> str: ...

@dataclass
class DescriptorState:
    values: weakref.WeakKeyDictionary = field(default_factory=weakref.WeakKeyDictionary)

def validate_type(value: Any, expected_type: type[DescriptorT]) -> bool: ...
