"""nudle -- UI fabric for Nu."""

from . import cli, interactions, page, protocol, refs, session
from .interactions import Append, Changed, Write
from .page import Index, Page, Pages
from .protocol import Frame, decode, encode
from .refs import (
    AccordionRef,
    AlertRef,
    AreaChart,
    BadgeRef,
    BarChart,
    ButtonRef,
    CardRef,
    CheckboxRef,
    CodeBlockRef,
    Column,
    Container,
    DatePickerRef,
    DividerRef,
    FieldRef,
    Fieldset,
    Form,
    GaugeRef,
    HeadingRef,
    ImageRef,
    InputRef,
    JsonViewerRef,
    LineChart,
    LinkRef,
    MarkdownRef,
    Modal,
    NavRef,
    NudleRef,
    NumberInputRef,
    PieChart,
    ProgressRef,
    RadioGroupRef,
    Row,
    Section,
    SelectRef,
    SliderRef,
    Sparkline,
    StatRef,
    SwitchRef,
    TableRef,
    TabsRef,
    TagInputRef,
    TextAreaRef,
    TextRef,
    TitleRef,
)
from .serve import serve
from .session import NudleSession, Subscription


__all__ = [
    # Submodules
    "cli",
    "interactions",
    "page",
    "protocol",
    "refs",
    "session",
    # Names
    "AccordionRef",
    "AlertRef",
    "Append",
    "AreaChart",
    "BadgeRef",
    "BarChart",
    "ButtonRef",
    "CardRef",
    "Changed",
    "CheckboxRef",
    "CodeBlockRef",
    "Column",
    "Container",
    "DatePickerRef",
    "DividerRef",
    "FieldRef",
    "Fieldset",
    "Form",
    "Frame",
    "GaugeRef",
    "HeadingRef",
    "ImageRef",
    "Index",
    "InputRef",
    "JsonViewerRef",
    "LineChart",
    "LinkRef",
    "MarkdownRef",
    "Modal",
    "NavRef",
    "NudleRef",
    "NudleSession",
    "NumberInputRef",
    "Page",
    "Pages",
    "PieChart",
    "ProgressRef",
    "RadioGroupRef",
    "Row",
    "Section",
    "SelectRef",
    "SliderRef",
    "Sparkline",
    "StatRef",
    "Subscription",
    "SwitchRef",
    "TableRef",
    "TabsRef",
    "TagInputRef",
    "TextAreaRef",
    "TextRef",
    "TitleRef",
    "Write",
    "decode",
    "encode",
    "serve",
]
