from __future__ import annotations

from .tree.backend import (
    CallbackFn,
    Key,
    KeyBase,
    ObservableStorage,
    ObservableStorageProtocol,
    ObservableStorageSnapshot,
    ObservableStorageSnapshotContextManager,
    ObservableStorageTransaction,
    ObservableStorageTransactionContextManager,
    ObserverProtocol,
    SnapshotContextManagerProtocol,
    SnapshotHandlerProtocol,
    SnapshotProtocol,
    StorageError,
    StorageKeyError,
    StorageProtocol,
    SubscriptionProtocol,
    TransactionalHandlerProtocol,
    TransactionContextManagerProtocol,
    TransactionProtocol,
    Value,
    ValueT,
    ValueT_co,
    ValueT_contra,
)
from .tree.path import ExtendedPath, Path, PathResolver
from .tree.query import Query
from .tree.tree import (
    EMPTY,
    BaseNode,
    BaseView,
    ChildInfo,
    ChildType,
    ContainerInfo,
    ContainerNode,
    ContainerProtocol,
    ContainerStructure,
    ContextProtocol,
    ContextType,
    ContextualBase,
    DictView,
    Empty,
    ListView,
    PrimitiveNode,
    SnapshotContextProtocol,
    TransactionContextProtocol,
    Tree,
    TreeT,
    ViewT,
    create_context,
    create_view_context_manager,
    is_contextual,
    is_empty,
    with_context,
)


__all__ = [
    # backend
    "StorageProtocol",
    "SnapshotProtocol",
    "SnapshotContextManagerProtocol",
    "SnapshotHandlerProtocol",
    "TransactionProtocol",
    "TransactionContextManagerProtocol",
    "TransactionalHandlerProtocol",
    "ObservableStorageProtocol",
    "ObserverProtocol",
    "SubscriptionProtocol",
    "KeyBase",
    "Key",
    "Value",
    "CallbackFn",
    "ValueT",
    "ValueT_co",
    "ValueT_contra",
    "ObservableStorage",
    "ObservableStorageTransactionContextManager",
    "ObservableStorageSnapshot",
    "ObservableStorageTransaction",
    "ObservableStorageSnapshotContextManager",
    "StorageError",
    "StorageKeyError",
    # tree
    "ContextProtocol",
    "ContextType",
    "ContextualBase",
    "SnapshotContextProtocol",
    "TransactionContextProtocol",
    "create_context",
    "is_contextual",
    "with_context",
    "BaseNode",
    "ChildInfo",
    "ChildType",
    "ContainerInfo",
    "ContainerNode",
    "PrimitiveNode",
    "Tree",
    "EMPTY",
    "Empty",
    "is_empty",
    "BaseView",
    "DictView",
    "ListView",
    "create_view_context_manager",
    "TreeT",
    "ViewT",
    "Value",
    "ContainerProtocol",
    "ContainerStructure",
    # path
    "Path",
    "ExtendedPath",
    "PathResolver",
    # query
    "Query",
]
