import abc
from abc import ABC
from dataclasses import dataclass
from typing import Any, Generic

from loomi.service import Spec
from loomistd.codec import CodecProtocol

from ._protocols import SubscriptionProtocol
from ._types import ObserverCallbackFn, ObserverEncodedKeyT, ObserverKeyT

__all__ = ["BaseObserver", "BaseObserverSpec", "Subscription"]

class BaseObserverSpec(Spec):
    codec: Spec
    @classmethod
    def identity_fields(cls) -> set[str]: ...

class BaseObserver(ABC, Generic[ObserverKeyT, ObserverEncodedKeyT], metaclass=abc.ABCMeta):
    @property
    def codec(self) -> CodecProtocol[ObserverKeyT, Any, ObserverEncodedKeyT, Any]: ...
    async def setup(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def notify(self, topic: ObserverKeyT) -> None: ...
    async def subscribe(
        self, topic_pattern: ObserverKeyT, callback: ObserverCallbackFn[ObserverKeyT]
    ) -> Subscription[ObserverKeyT]: ...
    async def unsubscribe(self, subscription: Subscription[ObserverKeyT]) -> None: ...

@dataclass
class Subscription(SubscriptionProtocol[ObserverKeyT]):
    @property
    def topic_pattern(self) -> ObserverKeyT: ...
    @property
    def callback(self) -> ObserverCallbackFn[ObserverKeyT]: ...
    def __init__(self, _topic_pattern, _callback) -> None: ...
