__all__ = [
    "ObserverError",
    "ObserverConnectionError",
    "ObserverSubscriptionError",
    "ObserverValidationError",
]

class ObserverError(Exception): ...
class ObserverConnectionError(ObserverError): ...
class ObserverSubscriptionError(ObserverError): ...
class ObserverValidationError(ObserverError): ...
