from typing import Any, Protocol

from loomistd.codec import CodecProtocol

from ._types import ObserverCallbackFn, ObserverEncodedKeyT, ObserverKeyT

__all__ = ["ObserverProtocol", "SubscriptionProtocol"]

class ObserverProtocol(Protocol[ObserverKeyT, ObserverEncodedKeyT]):
    @property
    def codec(self) -> CodecProtocol[ObserverKeyT, Any, ObserverEncodedKeyT, Any]: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def notify(self, topic: ObserverKeyT) -> None: ...
    async def subscribe(
        self, topic_pattern: ObserverKeyT, callback: ObserverCallbackFn[ObserverKeyT]
    ) -> SubscriptionProtocol[ObserverKeyT]: ...
    async def unsubscribe(self, subscription: SubscriptionProtocol[ObserverKeyT]) -> None: ...

class SubscriptionProtocol(Protocol[ObserverKeyT]):
    @property
    def topic_pattern(self) -> ObserverKeyT: ...
    @property
    def callback(self) -> ObserverCallbackFn[ObserverKeyT]: ...
