from loomi.service.base import Service, Spec

__all__ = ["ServiceCommonComposer"]

class ServiceCommonComposer(Service):
    def add_dependency(self, name: str, spec: Spec) -> Service: ...
    def get_dependency(self, name: str) -> Service: ...
    def get_dependencies(self) -> dict[str, "Service"]: ...
    def get_dependents(self) -> set["Service"]: ...
    def detach_dependent(self, dependent: Service) -> None: ...
