"""Scalar queries — single-yield functional construction over operand values."""

from .access import At, Contains, Len, Slice
from .arithmetic import (
    Abs,
    Add,
    Div,
    FloorDiv,
    Mod,
    Mul,
    Neg,
    Pos,
    Pow,
    Sub,
)
from .attr import DelAttr, GetAttr, SetAttr
from .bitwise import (
    BitwiseAnd,
    BitwiseNot,
    BitwiseOr,
    LShift,
    RShift,
    Xor,
)
from .call import (
    FuncCall,
    FuncCallCmd,
    MethodCall,
    MethodCallCmd,
)
from .combine import Chain, Enumerate, Zip
from .combiners import all_, and_, any_, none_, or_
from .comparison import (
    Eq,
    Ge,
    Gt,
    IdComp,
    Le,
    Lt,
    Ne,
)
from .control import If, Switch
from .conversion import (
    ToBool,
    ToBytes,
    ToFloat,
    ToInt,
    ToList,
    ToSet,
    ToStr,
    ToTuple,
)
from .logical import (
    And,
    Bool,
    Not,
    Or,
)
from .reduce import All, Any, Max, Min, Sum
from .sentinel import IsEmpty, IsInvalid, NotEmpty, NotInvalid
from .slice import Drop, Take
from .transform import (
    FilterBy,
    Flatten,
    Pluck,
    Reversed,
    Sorted,
    Unique,
)


__all__ = [
    "Abs",
    "Add",
    "All",
    "And",
    "Any",
    "At",
    "BitwiseAnd",
    "BitwiseNot",
    "BitwiseOr",
    "Bool",
    "Chain",
    "Contains",
    "DelAttr",
    "Div",
    "Drop",
    "Enumerate",
    "Eq",
    "FilterBy",
    "Flatten",
    "FloorDiv",
    "FuncCall",
    "FuncCallCmd",
    "Ge",
    "GetAttr",
    "Gt",
    "IdComp",
    "If",
    "IsEmpty",
    "IsInvalid",
    "LShift",
    "Le",
    "Len",
    "Lt",
    "Max",
    "MethodCall",
    "MethodCallCmd",
    "Min",
    "Mod",
    "Mul",
    "Ne",
    "Neg",
    "Not",
    "NotEmpty",
    "NotInvalid",
    "Or",
    "Pluck",
    "Pos",
    "Pow",
    "RShift",
    "Reversed",
    "SetAttr",
    "Slice",
    "Sorted",
    "Switch",
    "Sub",
    "Sum",
    "Take",
    "ToBool",
    "ToBytes",
    "ToFloat",
    "ToInt",
    "ToList",
    "ToSet",
    "ToStr",
    "ToTuple",
    "Unique",
    "Xor",
    "Zip",
    "all_",
    "and_",
    "any_",
    "none_",
    "or_",
]
