"""Generic collection interfaces and interactions."""

from nu.core.access import SetItem

from .collection import CollectionForm
from .container import ContainerForm
from .iterable import IterableForm
from .mapping import MappingForm, MutableMappingForm, ReactiveMappingForm
from .mapping_interactions import (
    ContainsKey,
    DeleteItem,
    DictPop,
    Get,
    Items,
    Keys,
    Merge,
    MergeUpdate,
    PopItem,
    ReversedItems,
    ReversedKeys,
    ReversedValues,
    SetDefault,
    Update,
    Values,
)
from .sequence import MutableSequenceForm, ReactiveSequenceForm, SequenceForm
from .sequence_interactions import (
    Append,
    Count,
    DelIndex,
    Extend,
    First,
    IAdd,
    IMul,
    IndexOf,
    Insert,
    Last,
    Pop,
    RemoveValue,
    Reverse,
    SetIndex,
    Sort,
)
from .set_ import MutableSetForm, ReactiveSetForm, SetLikeForm
from .set_interactions import (
    AddCmd,
    Difference,
    DifferenceUpdate,
    Discard,
    Intersection,
    IntersectionUpdate,
    IsDisjoint,
    IsSubset,
    IsSuperset,
    Remove,
    SetAnd,
    SetIAnd,
    SetIOr,
    SetISub,
    SetIXor,
    SetOr,
    SetPop,
    SetSub,
    SetUpdate,
    SetXor,
    SymmetricDifference,
    SymmetricDifferenceUpdate,
    Union,
)
from .shared_interactions import Clear
from .sized import SizedForm
from .sliceable import SliceableForm


__all__ = [
    "AddCmd",
    "Append",
    "Clear",
    "CollectionForm",
    "ContainerForm",
    "ContainsKey",
    "Count",
    "DelIndex",
    "DeleteItem",
    "DictPop",
    "Difference",
    "DifferenceUpdate",
    "Discard",
    "Extend",
    "First",
    "Get",
    "IAdd",
    "IMul",
    "IndexOf",
    "Insert",
    "Intersection",
    "IntersectionUpdate",
    "IsDisjoint",
    "IsSubset",
    "IsSuperset",
    "Items",
    "IterableForm",
    "Keys",
    "Last",
    "MappingForm",
    "Merge",
    "MergeUpdate",
    "MutableMappingForm",
    "MutableSequenceForm",
    "MutableSetForm",
    "Pop",
    "PopItem",
    "ReactiveMappingForm",
    "ReactiveSequenceForm",
    "ReactiveSetForm",
    "Remove",
    "RemoveValue",
    "Reverse",
    "ReversedItems",
    "ReversedKeys",
    "ReversedValues",
    "SequenceForm",
    "SetAnd",
    "SetDefault",
    "SetIAnd",
    "SetIOr",
    "SetISub",
    "SetIXor",
    "SetIndex",
    "SetItem",
    "SetLikeForm",
    "SetOr",
    "SetPop",
    "SetSub",
    "SetUpdate",
    "SetXor",
    "SizedForm",
    "SliceableForm",
    "Sort",
    "SymmetricDifference",
    "SymmetricDifferenceUpdate",
    "Union",
    "Update",
    "Values",
]
