import abc
from abc import ABC
from typing import AsyncGenerator, Generic, TypeGuard

from loomi.service import Spec
from loomistd.codec import CodecProtocol

from ._protocols import TransactionProtocol
from ._transaction import TransactionContextManager
from ._types import (
    StorageEncodedKeyT,
    StorageEncodedValueT,
    StorageKeyT,
    StorageMode,
    StorageValueT,
)

__all__ = ["BaseStorage", "BaseStorageSpec", "is_valid_key"]

class BaseStorageSpec(Spec):
    codec: Spec
    mode: StorageMode
    @classmethod
    def identity_fields(cls) -> set[str]: ...

class BaseStorage(
    ABC,
    Generic[StorageKeyT, StorageValueT, StorageEncodedKeyT, StorageEncodedValueT],
    metaclass=abc.ABCMeta,
):
    @property
    def codec(
        self,
    ) -> CodecProtocol[StorageKeyT, StorageValueT, StorageEncodedKeyT, StorageEncodedValueT]: ...
    @property
    def mode(self) -> StorageMode: ...
    async def setup(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def get(self, key: StorageKeyT) -> StorageValueT: ...
    async def set(self, key: StorageKeyT, value: StorageValueT) -> None: ...
    async def delete(self, key: StorageKeyT) -> None: ...
    async def exists(self, key: StorageKeyT) -> bool: ...
    async def list_keys(self, prefix: StorageKeyT) -> AsyncGenerator[StorageKeyT, None]: ...
    async def begin_transaction(self) -> TransactionProtocol[StorageKeyT, StorageValueT]: ...
    async def transaction(self) -> TransactionContextManager[StorageKeyT, StorageValueT]: ...

def is_valid_key(value: StorageKeyT) -> TypeGuard[StorageKeyT]: ...
