__all__ = [
    "StorageError",
    "StorageConnectionError",
    "StorageOperationError",
    "StorageKeyError",
    "StorageValidationError",
    "TransactionError",
    "TransactionConflictError",
    "TransactionInvalidError",
]

class StorageError(Exception): ...
class StorageConnectionError(StorageError): ...
class StorageOperationError(StorageError): ...
class StorageKeyError(StorageOperationError): ...
class StorageValidationError(StorageOperationError): ...
class TransactionError(StorageError): ...
class TransactionConflictError(TransactionError): ...
class TransactionInvalidError(TransactionError): ...
