from types import TracebackType
from typing import AsyncGenerator, Protocol

from loomistd.codec import CodecProtocol

from ._types import StorageEncodedKeyT, StorageEncodedValueT, StorageKeyT, StorageValueT

__all__ = [
    "StorageProtocol",
    "TransactionProtocol",
    "TransactionContextManagerProtocol",
    "TransactionalHandlerProtocol",
]

class StorageProtocol(
    Protocol[StorageKeyT, StorageValueT, StorageEncodedKeyT, StorageEncodedValueT]
):
    @property
    def codec(
        self,
    ) -> CodecProtocol[StorageKeyT, StorageValueT, StorageEncodedKeyT, StorageEncodedValueT]: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def get(self, key: StorageKeyT) -> StorageValueT: ...
    async def set(self, key: StorageKeyT, value: StorageValueT) -> None: ...
    async def delete(self, key: StorageKeyT) -> None: ...
    async def exists(self, key: StorageKeyT) -> bool: ...
    async def list_keys(self, prefix: StorageKeyT) -> AsyncGenerator[StorageKeyT, None]: ...
    async def begin_transaction(self) -> TransactionProtocol[StorageKeyT, StorageValueT]: ...
    async def transaction(
        self,
    ) -> TransactionContextManagerProtocol[StorageKeyT, StorageValueT]: ...

class TransactionProtocol(Protocol[StorageKeyT, StorageValueT]):
    async def get(self, key: StorageKeyT) -> StorageValueT: ...
    async def set(self, key: StorageKeyT, value: StorageValueT) -> None: ...
    async def delete(self, key: StorageKeyT) -> None: ...
    async def exists(self, key: StorageKeyT) -> bool: ...
    async def list_keys(self, prefix: StorageKeyT) -> AsyncGenerator[StorageKeyT, None]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

class TransactionContextManagerProtocol(Protocol[StorageKeyT, StorageValueT]):
    def __init__(
        self, handler: TransactionalHandlerProtocol[StorageKeyT, StorageValueT]
    ) -> None: ...
    async def __aenter__(self) -> TransactionProtocol[StorageKeyT, StorageValueT]: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class TransactionalHandlerProtocol(Protocol[StorageKeyT, StorageValueT]):
    async def begin_transaction(self) -> TransactionProtocol[StorageKeyT, StorageValueT]: ...
    async def transaction(
        self,
    ) -> TransactionContextManagerProtocol[StorageKeyT, StorageValueT]: ...
