"""Everybase - Foundation library for the every ecosystem.

Structure:
- capabilities/: Capability protocols and bases (NumericBase/Protocol, ComparableBase/Protocol, etc.)
- morphisms/: Concrete morphisms (AddOp, SubOp, EqOp, etc.)
- refs/: Abstract ref bases (IntType, StrType, etc.)
- py/: Python memory refs (IntValue, StrValue, ListValue, etc.)
- util/: Utilities (ensure_term, typed_value, combiners)
"""

# Re-export capabilities
from everybase.capabilities import (
    # Arithmetic
    AddableBase,
    AddableProtocol,
    AdditiveBase,
    AdditiveProtocol,
    # Logical
    AndableBase,
    AndableProtocol,
    # Bitwise
    BitwiseAndableBase,
    BitwiseAndableProtocol,
    BitwiseBase,
    BitwiseInvertableBase,
    BitwiseInvertableProtocol,
    BitwiseOrableBase,
    BitwiseOrableProtocol,
    BitwiseProtocol,
    BitwiseXorableBase,
    BitwiseXorableProtocol,
    # Clearable
    ClearableBase,
    ClearableProtocol,
    # Collection: combined
    CollectionBase,
    # Location: collection (bases)
    CollectionClearableBase,
    CollectionExistableBase,
    CollectionExtractableBase,
    CollectionLengthableBase,
    CollectionProtocol,
    CollectionStorableBase,
    # Comparison
    ComparableBase,
    ComparableProtocol,
    # Collection atoms
    ContainableBase,
    ContainableProtocol,
    DivisibleBase,
    DivisibleProtocol,
    EqualableBase,
    EqualableProtocol,
    IndexableBase,
    IndexableProtocol,
    # Location: item access (bases)
    ItemDeletableBase,
    ItemExistableBase,
    ItemGettableBase,
    ItemSettableBase,
    # Collection: iterable
    IterableBase,
    IterableProtocol,
    LengthableBase,
    LengthableProtocol,
    # Location capabilities (protocol-only)
    LocationDeletableProtocol,
    LocationExistableProtocol,
    LocationGettableProtocol,
    LocationObservableProtocol,
    LocationSettableProtocol,
    LogicalBase,
    LogicalProtocol,
    MappingBase,
    MappingProtocol,
    ModuloableBase,
    ModuloableProtocol,
    MultiplicativeBase,
    MultiplicativeProtocol,
    MultiplyableBase,
    MultiplyableProtocol,
    # Mutable collection capabilities
    MutableMappingBase,
    MutableMappingProtocol,
    MutableSequenceBase,
    MutableSequenceProtocol,
    MutableSetBase,
    MutableSetProtocol,
    NegatableBase,
    NegatableProtocol,
    NotableBase,
    NotableProtocol,
    NumericBase,
    NumericProtocol,
    OrableBase,
    OrableProtocol,
    OrderableBase,
    OrderableProtocol,
    PowerableBase,
    PowerableProtocol,
    # Location: reactive (bases)
    PrimitiveObservableBase,
    SequenceBase,
    SequenceProtocol,
    SetLikeBase,
    SetLikeProtocol,
    ShiftableBase,
    ShiftableProtocol,
    SliceableBase,
    SliceableProtocol,
    SubtractableBase,
    SubtractableProtocol,
    ViewObservableBase,
)

# Re-export utilities
from everybase.combiners import all_, and_, any_, coalesce, ifelse, none_, or_
from everybase.morphisms import (
    # Arithmetic
    AbsOp,
    # Collection mutations (impure)
    AddCmd,
    AddOp,
    # Collection (pure)
    AllOp,
    # Logical
    AndOp,
    AnyOp,
    AppendCmd,
    AtOp,
    # Bitwise
    BitwiseAndOp,
    BitwiseNotOp,
    BitwiseOrOp,
    BoolOp,
    # Location: reactive
    ChangeOp,
    ClearCmd,
    # Location: collection
    CollectionClearCmd,
    CollectionExistsOp,
    CollectionLenOp,
    CollectionMissingOp,
    # Conditional
    ConditionalOp,
    ContainsOp,
    CountOp,
    # Callable
    DelAttrOp,
    DeleteItemCmd,
    DiscardCmd,
    DivOp,
    # Comparison
    EqOp,
    ExtractOp,
    FilterOp,
    FindIndexOp,
    FindOp,
    FirstOp,
    FloorDivOp,
    FuncCallOp,
    GeOp,
    GetAttrOp,
    GtOp,
    IdCompOp,
    IndexOfOp,
    InsertCmd,
    # Special
    IsEmptyOp,
    IsNaNOp,
    # Location: item access
    ItemDeleteCmd,
    ItemExistsOp,
    ItemGetOp,
    ItemMissingOp,
    ItemSetCmd,
    JoinOp,
    LastOp,
    LenOp,
    LeOp,
    LShiftOp,
    LtOp,
    MapOp,
    MaxOp,
    MethodCallOp,
    MinOp,
    ModOp,
    MulOp,
    NegOp,
    NeOp,
    NotEmptyOp,
    NotNaNOp,
    NotOp,
    OnChangeOp,
    OnChildChangeOp,
    OnChildrenChangeOp,
    OnDescendantsChangeOp,
    OnPrimitiveChangeOp,
    OrOp,
    PopCmd,
    PosOp,
    PowOp,
    ReduceOp,
    RemoveCmd,
    ReversedOp,
    RShiftOp,
    SetAttrOp,
    SetItemCmd,
    SliceOp,
    SortedOp,
    StoreCmd,
    SubOp,
    SumOp,
    # Conversion
    ToBoolOp,
    ToBytesOp,
    ToFloatOp,
    ToIntOp,
    ToListOp,
    ToSetOp,
    ToStrOp,
    ToTupleOp,
    UpdateCmd,
    XorOp,
)

# Re-export ref bases
from everybase.types import (
    AnyType,
    BoolType,
    BytesType,
    DictType,
    EmptyType,
    FloatType,
    FrozenSetType,
    IntType,
    InvalidType,
    ListType,
    NoneType,
    SentinelType,
    SetType,
    StrType,
    TupleType,
    TypeBase,
)
from everybase.utils import ensure_term, typed_value

# Re-export py refs
from everybase.values import (
    AnyValue,
    BoolValue,
    BytesValue,
    DictValue,
    EmptyValue,
    FloatValue,
    FrozenSetValue,
    IntValue,
    InvalidValue,
    ListValue,
    NoneValue,
    SentinelValue,
    SetValue,
    StrValue,
    TupleValue,
    ValueBase,
)


__all__ = [  # noqa: RUF022
    # =========================================================================
    # CAPABILITIES (protocols + bases)
    # =========================================================================
    # Arithmetic
    "AddableBase",
    "AddableProtocol",
    "SubtractableBase",
    "SubtractableProtocol",
    "NegatableBase",
    "NegatableProtocol",
    "MultiplyableBase",
    "MultiplyableProtocol",
    "DivisibleBase",
    "DivisibleProtocol",
    "ModuloableBase",
    "ModuloableProtocol",
    "PowerableBase",
    "PowerableProtocol",
    "AdditiveBase",
    "AdditiveProtocol",
    "MultiplicativeBase",
    "MultiplicativeProtocol",
    "NumericBase",
    "NumericProtocol",
    # Comparison
    "OrderableBase",
    "OrderableProtocol",
    "EqualableBase",
    "EqualableProtocol",
    "ComparableBase",
    "ComparableProtocol",
    # Logical
    "AndableBase",
    "AndableProtocol",
    "OrableBase",
    "OrableProtocol",
    "NotableBase",
    "NotableProtocol",
    "LogicalBase",
    "LogicalProtocol",
    # Bitwise
    "BitwiseAndableBase",
    "BitwiseAndableProtocol",
    "BitwiseOrableBase",
    "BitwiseOrableProtocol",
    "BitwiseXorableBase",
    "BitwiseXorableProtocol",
    "BitwiseInvertableBase",
    "BitwiseInvertableProtocol",
    "ShiftableBase",
    "ShiftableProtocol",
    "BitwiseBase",
    "BitwiseProtocol",
    # Collection atoms
    "ContainableBase",
    "ContainableProtocol",
    "LengthableBase",
    "LengthableProtocol",
    "IndexableBase",
    "IndexableProtocol",
    "SliceableBase",
    "SliceableProtocol",
    # Collection: iterable
    "IterableBase",
    "IterableProtocol",
    # Collection: combined
    "CollectionBase",
    "CollectionProtocol",
    "SequenceBase",
    "SequenceProtocol",
    "MappingBase",
    "MappingProtocol",
    "SetLikeBase",
    "SetLikeProtocol",
    # Mutable collection
    "MutableSequenceBase",
    "MutableSequenceProtocol",
    "MutableMappingBase",
    "MutableMappingProtocol",
    "MutableSetBase",
    "MutableSetProtocol",
    "ClearableBase",
    "ClearableProtocol",
    # Location capabilities (protocol-only)
    "LocationGettableProtocol",
    "LocationSettableProtocol",
    "LocationExistableProtocol",
    "LocationDeletableProtocol",
    "LocationObservableProtocol",
    # Location: item access (bases)
    "ItemGettableBase",
    "ItemSettableBase",
    "ItemDeletableBase",
    "ItemExistableBase",
    # Location: collection (bases)
    "CollectionExtractableBase",
    "CollectionStorableBase",
    "CollectionLengthableBase",
    "CollectionClearableBase",
    "CollectionExistableBase",
    # Location: reactive (bases)
    "PrimitiveObservableBase",
    "ViewObservableBase",
    # =========================================================================
    # MORPHISMS (operations + commands)
    # =========================================================================
    # Arithmetic
    "AbsOp",
    "AddOp",
    "DivOp",
    "FloorDivOp",
    "ModOp",
    "MulOp",
    "NegOp",
    "PosOp",
    "PowOp",
    "SubOp",
    # Comparison
    "EqOp",
    "GeOp",
    "GtOp",
    "IdCompOp",
    "LeOp",
    "LtOp",
    "NeOp",
    # Logical
    "AndOp",
    "BoolOp",
    "NotOp",
    "OrOp",
    # Bitwise
    "BitwiseAndOp",
    "BitwiseNotOp",
    "BitwiseOrOp",
    "LShiftOp",
    "RShiftOp",
    "XorOp",
    # Conversion
    "ToBoolOp",
    "ToBytesOp",
    "ToFloatOp",
    "ToIntOp",
    "ToListOp",
    "ToSetOp",
    "ToStrOp",
    "ToTupleOp",
    # Special
    "IsEmptyOp",
    "IsNaNOp",
    "NotEmptyOp",
    "NotNaNOp",
    # Conditional
    "ConditionalOp",
    # Callable
    "DelAttrOp",
    "FuncCallOp",
    "GetAttrOp",
    "MethodCallOp",
    "SetAttrOp",
    # Collection
    "AllOp",
    "AnyOp",
    "AtOp",
    "ContainsOp",
    "CountOp",
    "FilterOp",
    "FindIndexOp",
    "FindOp",
    "FirstOp",
    "IndexOfOp",
    "JoinOp",
    "LastOp",
    "LenOp",
    "MapOp",
    "MaxOp",
    "MinOp",
    "ReduceOp",
    "ReversedOp",
    "SliceOp",
    "SortedOp",
    "SumOp",
    # Collection mutations (impure)
    "AddCmd",
    "AppendCmd",
    "ClearCmd",
    "DeleteItemCmd",
    "DiscardCmd",
    "InsertCmd",
    "PopCmd",
    "RemoveCmd",
    "SetItemCmd",
    "UpdateCmd",
    # Location: item access morphisms
    "ItemGetOp",
    "ItemSetCmd",
    "ItemDeleteCmd",
    "ItemExistsOp",
    "ItemMissingOp",
    # Location: collection morphisms
    "ExtractOp",
    "StoreCmd",
    "CollectionLenOp",
    "CollectionClearCmd",
    "CollectionExistsOp",
    "CollectionMissingOp",
    # Location: reactive morphisms
    "ChangeOp",
    "OnChangeOp",
    "OnPrimitiveChangeOp",
    "OnChildChangeOp",
    "OnChildrenChangeOp",
    "OnDescendantsChangeOp",
    # =========================================================================
    # REFS (Python memory)
    # =========================================================================
    "ValueBase",
    "IntValue",
    "FloatValue",
    "BoolValue",
    "StrValue",
    "BytesValue",
    "ListValue",
    "SetValue",
    "DictValue",
    "FrozenSetValue",
    "TupleValue",
    "AnyValue",
    "NoneValue",
    "SentinelValue",
    "EmptyValue",
    "InvalidValue",
    # =========================================================================
    # REF BASES (abstract)
    # =========================================================================
    "TypeBase",
    "IntType",
    "FloatType",
    "BoolType",
    "StrType",
    "BytesType",
    "ListType",
    "DictType",
    "SetType",
    "FrozenSetType",
    "TupleType",
    "AnyType",
    "NoneType",
    "SentinelType",
    "EmptyType",
    "InvalidType",
    # =========================================================================
    # UTILITIES
    # =========================================================================
    "ensure_term",
    "typed_value",
    "all_",
    "and_",
    "any_",
    "or_",
    "coalesce",
    "ifelse",
    "none_",
]
