"""Everybase - Foundation library for the every ecosystem.

Structure:
- capabilities/: Capability protocols and bases (NumericBase/Protocol, ComparableBase/Protocol, etc.)
- morphisms/: Concrete morphisms (AddOp, SubOp, EqOp, etc.)
- refs/: Abstract ref bases (IntRefBase, StrRefBase, etc.)
- py/: Python memory refs (IntRef, StrRef, ListRef, etc.)
- util/: Utilities (ensure_term, typed_ref, combiners)
"""

# Re-export capabilities
from everybase.capabilities import (
    # Arithmetic
    AddableBase,
    AddableProtocol,
    AdditiveBase,
    AdditiveProtocol,
    # Logical
    AndableBase,
    AndableProtocol,
    # Bitwise
    BitwiseAndableBase,
    BitwiseAndableProtocol,
    BitwiseBase,
    BitwiseInvertableBase,
    BitwiseInvertableProtocol,
    BitwiseOrableBase,
    BitwiseOrableProtocol,
    BitwiseProtocol,
    BitwiseXorableBase,
    BitwiseXorableProtocol,
    # Collection: combined
    CollectionBase,
    CollectionProtocol,
    # Comparison
    ComparableBase,
    ComparableProtocol,
    # Collection atoms
    ContainableBase,
    ContainableProtocol,
    DivisibleBase,
    DivisibleProtocol,
    EqualableBase,
    EqualableProtocol,
    IndexableBase,
    IndexableProtocol,
    # Collection: iterable
    IterableBase,
    IterableProtocol,
    LengthableBase,
    LengthableProtocol,
    LogicalBase,
    LogicalProtocol,
    MappingBase,
    MappingProtocol,
    ModuloableBase,
    ModuloableProtocol,
    MultiplicativeBase,
    MultiplicativeProtocol,
    MultiplyableBase,
    MultiplyableProtocol,
    NegatableBase,
    NegatableProtocol,
    NotableBase,
    NotableProtocol,
    NumericBase,
    NumericProtocol,
    OrableBase,
    OrableProtocol,
    OrderableBase,
    OrderableProtocol,
    PowerableBase,
    PowerableProtocol,
    SequenceBase,
    SequenceProtocol,
    SetLikeBase,
    SetLikeProtocol,
    ShiftableBase,
    ShiftableProtocol,
    SliceableBase,
    SliceableProtocol,
    SubtractableBase,
    SubtractableProtocol,
)

# Re-export utilities
from everybase.combiners import all_, and_, any_, coalesce, ifelse, none_, or_
from everybase.morphisms import (
    # Arithmetic
    AbsOp,
    AddOp,
    # Collection
    AllOp,
    # Logical
    AndOp,
    AnyOp,
    AtOp,
    # Bitwise
    BitwiseAndOp,
    BitwiseNotOp,
    BitwiseOrOp,
    BoolOp,
    # Conditional
    ConditionalOp,
    ContainsOp,
    CountOp,
    # Callable
    DelAttrOp,
    DivOp,
    # Comparison
    EqOp,
    FilterOp,
    FindIndexOp,
    FindOp,
    FirstOp,
    FloorDivOp,
    FuncCallOp,
    GeOp,
    GetAttrOp,
    GtOp,
    IdCompOp,
    IndexOfOp,
    # Special
    IsEmptyOp,
    IsNaNOp,
    JoinOp,
    LastOp,
    LenOp,
    LeOp,
    LShiftOp,
    LtOp,
    MapOp,
    MaxOp,
    MethodCallOp,
    MinOp,
    ModOp,
    MulOp,
    NegOp,
    NeOp,
    NotEmptyOp,
    NotNaNOp,
    NotOp,
    OrOp,
    PosOp,
    PowOp,
    ReduceOp,
    ReversedOp,
    RShiftOp,
    SetAttrOp,
    SliceOp,
    SortedOp,
    SubOp,
    SumOp,
    # Conversion
    ToBoolOp,
    ToBytesOp,
    ToFloatOp,
    ToIntOp,
    ToListOp,
    ToSetOp,
    ToStrOp,
    ToTupleOp,
    XorOp,
)

# Re-export py refs
from everybase.py import (
    AnyRef,
    BoolRef,
    BytesRef,
    DictRef,
    EmptyRef,
    FloatRef,
    FrozenSetRef,
    IntRef,
    InvalidRef,
    ListRef,
    NoneRef,
    PyRefBase,
    SentinelRef,
    SetRef,
    StrRef,
    TupleRef,
)

# Re-export ref bases
from everybase.refs import (
    AnyRefBase,
    BoolRefBase,
    BytesRefBase,
    DictRefBase,
    EmptyRefBase,
    FloatRefBase,
    FrozenSetRefBase,
    IntRefBase,
    InvalidRefBase,
    ListRefBase,
    NoneRefBase,
    RefBase,
    SentinelRefBase,
    SetRefBase,
    StrRefBase,
    TupleRefBase,
)
from everybase.utils import ensure_term, typed_ref


__all__ = [  # noqa: RUF022
    # =========================================================================
    # CAPABILITIES (protocols + bases)
    # =========================================================================
    # Arithmetic
    "AddableBase",
    "AddableProtocol",
    "SubtractableBase",
    "SubtractableProtocol",
    "NegatableBase",
    "NegatableProtocol",
    "MultiplyableBase",
    "MultiplyableProtocol",
    "DivisibleBase",
    "DivisibleProtocol",
    "ModuloableBase",
    "ModuloableProtocol",
    "PowerableBase",
    "PowerableProtocol",
    "AdditiveBase",
    "AdditiveProtocol",
    "MultiplicativeBase",
    "MultiplicativeProtocol",
    "NumericBase",
    "NumericProtocol",
    # Comparison
    "OrderableBase",
    "OrderableProtocol",
    "EqualableBase",
    "EqualableProtocol",
    "ComparableBase",
    "ComparableProtocol",
    # Logical
    "AndableBase",
    "AndableProtocol",
    "OrableBase",
    "OrableProtocol",
    "NotableBase",
    "NotableProtocol",
    "LogicalBase",
    "LogicalProtocol",
    # Bitwise
    "BitwiseAndableBase",
    "BitwiseAndableProtocol",
    "BitwiseOrableBase",
    "BitwiseOrableProtocol",
    "BitwiseXorableBase",
    "BitwiseXorableProtocol",
    "BitwiseInvertableBase",
    "BitwiseInvertableProtocol",
    "ShiftableBase",
    "ShiftableProtocol",
    "BitwiseBase",
    "BitwiseProtocol",
    # Collection atoms
    "ContainableBase",
    "ContainableProtocol",
    "LengthableBase",
    "LengthableProtocol",
    "IndexableBase",
    "IndexableProtocol",
    "SliceableBase",
    "SliceableProtocol",
    # Collection: iterable
    "IterableBase",
    "IterableProtocol",
    # Collection: combined
    "CollectionBase",
    "CollectionProtocol",
    "SequenceBase",
    "SequenceProtocol",
    "MappingBase",
    "MappingProtocol",
    "SetLikeBase",
    "SetLikeProtocol",
    # =========================================================================
    # MORPHISMS (operations)
    # =========================================================================
    # Arithmetic
    "AbsOp",
    "AddOp",
    "DivOp",
    "FloorDivOp",
    "ModOp",
    "MulOp",
    "NegOp",
    "PosOp",
    "PowOp",
    "SubOp",
    # Comparison
    "EqOp",
    "GeOp",
    "GtOp",
    "IdCompOp",
    "LeOp",
    "LtOp",
    "NeOp",
    # Logical
    "AndOp",
    "BoolOp",
    "NotOp",
    "OrOp",
    # Bitwise
    "BitwiseAndOp",
    "BitwiseNotOp",
    "BitwiseOrOp",
    "LShiftOp",
    "RShiftOp",
    "XorOp",
    # Conversion
    "ToBoolOp",
    "ToBytesOp",
    "ToFloatOp",
    "ToIntOp",
    "ToListOp",
    "ToSetOp",
    "ToStrOp",
    "ToTupleOp",
    # Special
    "IsEmptyOp",
    "IsNaNOp",
    "NotEmptyOp",
    "NotNaNOp",
    # Conditional
    "ConditionalOp",
    # Callable
    "DelAttrOp",
    "FuncCallOp",
    "GetAttrOp",
    "MethodCallOp",
    "SetAttrOp",
    # Collection
    "AllOp",
    "AnyOp",
    "AtOp",
    "ContainsOp",
    "CountOp",
    "FilterOp",
    "FindIndexOp",
    "FindOp",
    "FirstOp",
    "IndexOfOp",
    "JoinOp",
    "LastOp",
    "LenOp",
    "MapOp",
    "MaxOp",
    "MinOp",
    "ReduceOp",
    "ReversedOp",
    "SliceOp",
    "SortedOp",
    "SumOp",
    # =========================================================================
    # REFS (Python memory)
    # =========================================================================
    "PyRefBase",
    "IntRef",
    "FloatRef",
    "BoolRef",
    "StrRef",
    "BytesRef",
    "ListRef",
    "SetRef",
    "DictRef",
    "FrozenSetRef",
    "TupleRef",
    "AnyRef",
    "NoneRef",
    "SentinelRef",
    "EmptyRef",
    "InvalidRef",
    # =========================================================================
    # REF BASES (abstract)
    # =========================================================================
    "RefBase",
    "IntRefBase",
    "FloatRefBase",
    "BoolRefBase",
    "StrRefBase",
    "BytesRefBase",
    "ListRefBase",
    "DictRefBase",
    "SetRefBase",
    "FrozenSetRefBase",
    "TupleRefBase",
    "AnyRefBase",
    "NoneRefBase",
    "SentinelRefBase",
    "EmptyRefBase",
    "InvalidRefBase",
    # =========================================================================
    # UTILITIES
    # =========================================================================
    "ensure_term",
    "typed_ref",
    "all_",
    "and_",
    "any_",
    "or_",
    "coalesce",
    "ifelse",
    "none_",
]
