from types import TracebackType
from typing import AsyncGenerator, Generator, Protocol

from .types import AsyncStateCallbackFn, StateKey, StateValue, SyncStateCallbackFn

__all__ = [
    "AsyncStateProtocol",
    "AsyncSubscriptionProtocol",
    "AsyncTransactionProtocol",
    "AsyncTransactionContextManagerProtocol",
    "AsyncTransactionalHandlerProtocol",
    "SyncStateProtocol",
    "SyncSubscriptionProtocol",
    "SyncTransactionProtocol",
    "SyncTransactionContextManagerProtocol",
    "SyncTransactionalHandlerProtocol",
]

class AsyncStateProtocol(Protocol):
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(
        self, key: StateKey, callback: AsyncStateCallbackFn
    ) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(self, subscription: AsyncSubscriptionProtocol) -> None: ...
    async def begin_transaction(self) -> AsyncTransactionProtocol: ...
    async def transaction(self) -> AsyncTransactionContextManagerProtocol: ...

class AsyncSubscriptionProtocol(Protocol):
    @property
    def topic_pattern(self) -> StateKey: ...
    @property
    def callback(self) -> AsyncStateCallbackFn: ...

class AsyncTransactionProtocol(Protocol):
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

class AsyncTransactionContextManagerProtocol(Protocol):
    async def __aenter__(self) -> AsyncTransactionProtocol: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...

class AsyncTransactionalHandlerProtocol(Protocol):
    async def begin_transaction(self) -> AsyncTransactionProtocol: ...
    async def transaction(self) -> AsyncTransactionContextManagerProtocol: ...

class SyncStateProtocol(Protocol):
    def get(self, key: StateKey) -> StateValue: ...
    def set(self, key: StateKey, value: StateValue) -> None: ...
    def delete(self, key: StateKey) -> None: ...
    def exists(self, key: StateKey) -> bool: ...
    def list_keys(self, prefix: StateKey) -> Generator[StateKey, None, None]: ...
    def subscribe(
        self, key: StateKey, callback: SyncStateCallbackFn
    ) -> SyncSubscriptionProtocol: ...
    def unsubscribe(self, subscription: SyncSubscriptionProtocol) -> None: ...
    def begin_transaction(self) -> SyncTransactionProtocol: ...
    def transaction(self) -> SyncTransactionContextManagerProtocol: ...

class SyncSubscriptionProtocol(Protocol):
    topic_pattern: StateKey
    callback: SyncStateCallbackFn

class SyncTransactionProtocol(Protocol):
    def get(self, key: StateKey) -> StateValue: ...
    def set(self, key: StateKey, value: StateValue) -> None: ...
    def delete(self, key: StateKey) -> None: ...
    def exists(self, key: StateKey) -> bool: ...
    def list_keys(self, prefix: StateKey) -> Generator[StateKey, None, None]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

class SyncTransactionContextManagerProtocol(Protocol):
    def __init__(self, handler: SyncTransactionalHandlerProtocol) -> None: ...
    def __enter__(self) -> SyncTransactionProtocol: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class SyncTransactionalHandlerProtocol(Protocol):
    def begin_transaction(self) -> SyncTransactionProtocol: ...
    def transaction(self) -> SyncTransactionContextManagerProtocol: ...
