import abc
from typing import AsyncGenerator

from loomi.app.base import AsyncApp

from .base import AppCommonState
from .protocols import (
    AsyncStateProtocol,
    AsyncSubscriptionProtocol,
    AsyncTransactionContextManagerProtocol,
    AsyncTransactionProtocol,
)
from .types import AsyncStateCallbackFn, StateKey, StateValue

__all__ = ["AsyncAppState"]

class AsyncAppState(AppCommonState, AsyncApp, metaclass=abc.ABCMeta):
    @property
    def state(self) -> AsyncStateProtocol: ...
    @property
    def s(self) -> AsyncStateProtocol: ...
    @property
    def state_key(self) -> StateKey: ...
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(
        self, key: StateKey, callback: AsyncStateCallbackFn
    ) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(self, subscription: AsyncSubscriptionProtocol) -> None: ...
    async def begin_transaction(self) -> AsyncTransactionProtocol: ...
    async def transaction(self) -> AsyncTransactionContextManagerProtocol: ...
