import abc
from typing import AsyncGenerator

from loomi.app.base import AsyncApp

from .base import AppCommonState
from .protocols import (
    AsyncStateProtocol,
    AsyncSubscriptionProtocol,
    AsyncTransactionContextManagerProtocol,
    AsyncTransactionProtocol,
)
from .types import AsyncStateCallbackFn, StateKey, StateValue

__all__ = ["AsyncAppState"]

class AsyncAppState(AppCommonState, AsyncApp, metaclass=abc.ABCMeta):
    @property
    def state(self) -> AsyncStateProtocol: ...
    @property
    def s(self) -> AsyncStateProtocol: ...
    async def get(self, key: StateKey, local: bool = ...) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue, local: bool = ...) -> None: ...
    async def delete(self, key: StateKey, local: bool = ...) -> None: ...
    async def exists(self, key: StateKey, local: bool = ...) -> bool: ...
    async def list_keys(
        self, prefix: StateKey, local: bool = ...
    ) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(
        self, key: StateKey, callback: AsyncStateCallbackFn, local: bool = ...
    ) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(
        self, subscription: AsyncSubscriptionProtocol, local: bool = ...
    ) -> None: ...
    async def begin_transaction(self) -> AsyncTransactionProtocol: ...
    async def transaction(self) -> AsyncTransactionContextManagerProtocol: ...
