import abc
from typing import Generator

from loomi.app.base import SyncApp

from .base import AppCommonState
from .protocols import (
    SyncStateProtocol,
    SyncSubscriptionProtocol,
    SyncTransactionContextManagerProtocol,
    SyncTransactionProtocol,
)
from .types import StateKey, StateValue, SyncStateCallbackFn

__all__ = ["SyncAppState"]

class SyncAppState(AppCommonState, SyncApp, metaclass=abc.ABCMeta):
    @property
    def state(self) -> SyncStateProtocol: ...
    @property
    def s(self) -> SyncStateProtocol: ...
    def get(self, key: StateKey, local: bool = ...) -> StateValue: ...
    def set(self, key: StateKey, value: StateValue, local: bool = ...) -> None: ...
    def delete(self, key: StateKey, local: bool = ...) -> None: ...
    def exists(self, key: StateKey, local: bool = ...) -> bool: ...
    def list_keys(self, prefix: StateKey, local: bool = ...) -> Generator[StateKey, None, None]: ...
    def subscribe(
        self, key: StateKey, callback: SyncStateCallbackFn, local: bool = ...
    ) -> SyncSubscriptionProtocol: ...
    def unsubscribe(self, subscription: SyncSubscriptionProtocol) -> None: ...
    def begin_transaction(self) -> SyncTransactionProtocol: ...
    def transaction(self) -> SyncTransactionContextManagerProtocol: ...
