from typing import Generator, Generic, TypeVar

from loomi.app.handlers.state import SyncStateCallbackFn, SyncSubscriptionProtocol
from loomi.app.handlers.state.types import StateKey, StateValue

from .model_sync import SyncAppModel

__all__ = ["SyncModelValue"]

T = TypeVar("T", bound=StateValue)

class SyncModelValue(Generic[T]):
    def __init__(self, model: SyncAppModel, name: str) -> None: ...
    def get(self) -> T: ...
    def set(self, value: T) -> None: ...
    def delete(self) -> None: ...
    def exists(self) -> bool: ...
    def list_keys(self) -> Generator[StateKey, None, None]: ...
    def subscribe(self, callback: SyncStateCallbackFn) -> SyncSubscriptionProtocol: ...
    def unsubscribe(self, subscription: SyncSubscriptionProtocol) -> None: ...
