from typing import AsyncGenerator, Generic, TypeVar

from loomi.app.handlers.state import AsyncStateCallbackFn, AsyncSubscriptionProtocol
from loomi.app.handlers.state.types import StateKey, StateValue

from .model_async import AsyncAppModel

__all__ = ["AsyncModelValue"]

T = TypeVar("T", bound=StateValue)

class AsyncModelValue(Generic[T]):
    def __init__(self, model: AsyncAppModel, name: str) -> None: ...
    async def get(self) -> T: ...
    async def set(self, value: T) -> None: ...
    async def delete(self) -> None: ...
    async def exists(self) -> bool: ...
    async def list_keys(self) -> AsyncGenerator[StateKey, None]: ...
    async def subscribe(self, callback: AsyncStateCallbackFn) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(self, subscription: AsyncSubscriptionProtocol) -> None: ...
