from typing import AsyncGenerator, Generator, Protocol

from loomi.app.handlers.state import (
    AsyncStateCallbackFn,
    AsyncSubscriptionProtocol,
    StateKey,
    StateValue,
    SyncStateCallbackFn,
    SyncSubscriptionProtocol,
)

__all__ = ["SyncAccessorContextProtocol", "AsyncAccessorContextProtocol"]

class SyncAccessorContextProtocol(Protocol):
    def get(self, key: StateKey) -> StateValue: ...
    def set(self, key: StateKey, value: StateValue) -> None: ...
    def delete(self, key: StateKey) -> None: ...
    def exists(self, key: StateKey) -> bool: ...
    def list_keys(self, prefix: StateKey) -> Generator["StateKey", None, None]: ...
    def subscribe(
        self, key: StateKey, callback: SyncStateCallbackFn
    ) -> SyncSubscriptionProtocol: ...
    def unsubscribe(self, subscription: SyncSubscriptionProtocol) -> None: ...

class AsyncAccessorContextProtocol(Protocol):
    async def get(self, key: StateKey) -> StateValue: ...
    async def set(self, key: StateKey, value: StateValue) -> None: ...
    async def delete(self, key: StateKey) -> None: ...
    async def exists(self, key: StateKey) -> bool: ...
    async def list_keys(self, prefix: StateKey) -> AsyncGenerator["StateKey", None]: ...
    async def subscribe(
        self, key: StateKey, callback: AsyncStateCallbackFn
    ) -> AsyncSubscriptionProtocol: ...
    async def unsubscribe(self, subscription: AsyncSubscriptionProtocol) -> None: ...
