"""Types."""

from everyshape.typing.type.capabilities import (
    Absoluteable,
    Addable,
    Andable,
    BitwiseAndable,
    BitwiseInvertible,
    BitwiseOrable,
    BitwiseXorable,
    Comparable,
    Concatenable,
    Containable,
    Divisible,
    Equalable,
    FloorDivisible,
    Formattable,
    Indexable,
    Invertible,
    Iterable,
    LeftShiftable,
    Lengthable,
    Modulable,
    Multipliable,
    Negatable,
    Orable,
    Powerable,
    RightShiftable,
    Sliceable,
    Subtractable,
    is_addable,
    is_andable,
    is_comparable,
    is_containable,
    is_divisible,
    is_equalable,
    is_indexable,
    is_iterable,
    is_lengthable,
    is_multipliable,
    is_orable,
    is_sliceable,
    is_subtractable,
)


__all__ = [  # noqa: RUF022
    # Arithmetic capabilities
    "Addable",
    "Subtractable",
    "Multipliable",
    "Divisible",
    "FloorDivisible",
    "Modulable",
    "Powerable",
    "Negatable",
    "Absoluteable",
    # Comparison capabilities
    "Comparable",
    "Equalable",
    # Logical capabilities
    "Andable",
    "Orable",
    "Invertible",
    # Bitwise capabilities
    "BitwiseAndable",
    "BitwiseOrable",
    "BitwiseXorable",
    "BitwiseInvertible",
    "LeftShiftable",
    "RightShiftable",
    # Collection capabilities
    "Indexable",
    "Sliceable",
    "Lengthable",
    "Containable",
    "Iterable",
    # String capabilities
    "Concatenable",
    "Formattable",
    # Type guards
    "is_addable",
    "is_subtractable",
    "is_multipliable",
    "is_divisible",
    "is_comparable",
    "is_equalable",
    "is_andable",
    "is_orable",
    "is_indexable",
    "is_sliceable",
    "is_lengthable",
    "is_containable",
    "is_iterable",
]
