"""everybase — Core library for the every ecosystem.

Subpackages:
    core/  -- abstract tree/term/flow/span/context contracts
    abc/   -- base implementations: types, values, morphisms, capabilities
"""

from __future__ import annotations

from .core import (
    EMPTY,
    INVALID,
    Arg,
    BinaryCommand,
    BinaryMorphism,
    BinaryOperation,
    BoolArg,
    BytesArg,
    Command,
    Context,
    DictArg,
    Empty,
    Executable,
    FloatArg,
    Flow,
    FrozenSetArg,
    Handle,
    IntArg,
    Invalid,
    ListArg,
    LValue,
    Model,
    Morphism,
    NAryCommand,
    NAryMorphism,
    NAryOperation,
    Node,
    NoneArg,
    Operation,
    Ref,
    RValue,
    Sentinel,
    SetArg,
    Span,
    StrArg,
    Term,
    TernaryCommand,
    TernaryMorphism,
    TernaryOperation,
    Transform,
    TupleArg,
    UnaryCommand,
    UnaryMorphism,
    UnaryOperation,
    Value,
    ancestors,
    apply,
    bfs,
    compose,
    count,
    depth,
    find,
    find_first,
    graft,
    is_empty,
    is_invalid,
    is_sentinel,
    leaves,
    map_children,
    map_nodes,
    postorder,
    preorder,
    propagate_special,
    prune,
    replace,
    size,
    unwrap,
    wrap,
)


__all__ = [  # noqa: RUF022
    # Tree
    "Node",
    "Executable",
    # Term
    "Term",
    "LValue",
    "RValue",
    "Value",
    "Ref",
    "Morphism",
    "NAryMorphism",
    "UnaryMorphism",
    "BinaryMorphism",
    "TernaryMorphism",
    "Operation",
    "Command",
    "NAryOperation",
    "NAryCommand",
    "UnaryOperation",
    "UnaryCommand",
    "BinaryOperation",
    "BinaryCommand",
    "TernaryOperation",
    "TernaryCommand",
    # Sentinel
    "Sentinel",
    "Empty",
    "Invalid",
    "EMPTY",
    "INVALID",
    "is_empty",
    "is_invalid",
    "is_sentinel",
    "propagate_special",
    # Arg types
    "Arg",
    "IntArg",
    "FloatArg",
    "StrArg",
    "BoolArg",
    "BytesArg",
    "NoneArg",
    "ListArg",
    "DictArg",
    "SetArg",
    "FrozenSetArg",
    "TupleArg",
    # Model
    "Model",
    # Flow & Span
    "Flow",
    "Span",
    # Context
    "Context",
    "Handle",
    # Walk
    "preorder",
    "postorder",
    "bfs",
    "leaves",
    "ancestors",
    # Transform
    "Transform",
    "compose",
    "apply",
    "map_children",
    "map_nodes",
    "replace",
    "wrap",
    "unwrap",
    "graft",
    "prune",
    # Query
    "find",
    "find_first",
    "count",
    "size",
    "depth",
]
