"""nu.ui -- component fabric.

Host-specific bits (serve, session, Page/Pages/Index, presets, wire protocol)
moved to `nu.nudle.py` in the layer/language reorg. This module re-exports
them here so existing `import nu.ui as nu_ui` code keeps working. Prefer
`from nu.nudle.py import ...` in new code.
"""

from nu.nudle.py import interactions, presets, protocol, session
from nu.nudle.py.fabric import NudleServer
from nu.nudle.py.interactions import Append, Changed, Write
from nu.nudle.py.page import Index, Page, Pages
from nu.nudle.py.protocol import Frame, decode, encode
from nu.nudle.py.session import NudleSession, Subscription

from . import refs
from .refs import (
    AccordionRef,
    AlertRef,
    AreaChart,
    BadgeRef,
    BarChart,
    ButtonRef,
    CardRef,
    CheckboxRef,
    CodeBlockRef,
    Column,
    Container,
    DatePickerRef,
    DividerRef,
    FieldRef,
    Fieldset,
    Form,
    GaugeRef,
    HeadingRef,
    ImageRef,
    InputRef,
    JsonViewerRef,
    LineChart,
    LinkRef,
    MarkdownRef,
    Modal,
    NavRef,
    NudleRef,
    NumberInputRef,
    PieChart,
    ProgressRef,
    RadioGroupRef,
    Row,
    Section,
    SelectRef,
    SliderRef,
    Sparkline,
    StatRef,
    SwitchRef,
    TableRef,
    TabsRef,
    TagInputRef,
    TextAreaRef,
    TextRef,
    TitleRef,
)


__all__ = [
    # Names
    "AccordionRef",
    "AlertRef",
    "Append",
    "AreaChart",
    "BadgeRef",
    "BarChart",
    "ButtonRef",
    "CardRef",
    "Changed",
    "CheckboxRef",
    "CodeBlockRef",
    "Column",
    "Container",
    "DatePickerRef",
    "DividerRef",
    "FieldRef",
    "Fieldset",
    "Form",
    "Frame",
    "GaugeRef",
    "HeadingRef",
    "ImageRef",
    "Index",
    "InputRef",
    "JsonViewerRef",
    "LineChart",
    "LinkRef",
    "MarkdownRef",
    "Modal",
    "NavRef",
    "NudleRef",
    "NudleServer",
    "NudleSession",
    "NumberInputRef",
    "Page",
    "Pages",
    "PieChart",
    "ProgressRef",
    "RadioGroupRef",
    "Row",
    "Section",
    "SelectRef",
    "SliderRef",
    "Sparkline",
    "StatRef",
    "Subscription",
    "SwitchRef",
    "TableRef",
    "TabsRef",
    "TagInputRef",
    "TextAreaRef",
    "TextRef",
    "TitleRef",
    "Write",
    # Submodules
    "decode",
    "encode",
    "interactions",
    "page",
    "presets",
    "protocol",
    "refs",
    "session",
]
